# Generated by Django 4.0.4 on 2022-06-01 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('how_often', models.CharField(blank=True, choices=[('DS', 'Daily several times'), ('DO', 'Daily once'), ('WO', 'Weekly once'), ('MO', 'Monthly once'), ('YO', 'Yearly once')], max_length=2, null=True)),
                ('how_important_task', models.CharField(blank=True, choices=[('EI', 'Extremely important'), ('RI', 'Rather important'), ('LI', 'Less important')], max_length=2, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('why_perform_task', models.CharField(blank=True, max_length=150, null=True)),
                ('why_important_task', models.CharField(blank=True, max_length=150, null=True)),
                ('sequence_of_actions', models.CharField(blank=True, max_length=500, null=True)),
                ('tools_used', models.CharField(blank=True, max_length=150, null=True)),
                ('special_training_required', models.BooleanField(blank=True, default=False, null=True)),
                ('what_training_required', models.CharField(blank=True, max_length=150, null=True)),
                ('what_can_go_wrong', models.CharField(blank=True, max_length=150, null=True)),
                ('effects_of_task', models.CharField(blank=True, max_length=150, null=True)),
                ('special_vocabulary_used', models.CharField(blank=True, max_length=150, null=True)),
                ('people_involved', models.CharField(blank=True, max_length=150, null=True)),
                ('any_improvements', models.CharField(blank=True, max_length=150, null=True)),
                ('how_important_improvement', models.CharField(blank=True, choices=[('EI', 'Extremely important'), ('RI', 'Rather important'), ('LI', 'Less important')], max_length=2, null=True)),
                ('benefits_of_improvement', models.CharField(blank=True, max_length=150, null=True)),
                ('stakeholder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(blank=True, to='nestedm2m.task')),
            ],
        ),
    ]
