# Generated by Django 4.0.4 on 2022-06-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestedm2m', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='stakeholder',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
