# Generated by Django 4.0.4 on 2022-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nestedm2m', '0002_remove_task_stakeholder_delete_scenario_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllowOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_list', models.ManyToManyField(to='nestedm2m.iplist')),
            ],
        ),
    ]
