# Generated by Django 4.0.4 on 2022-05-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='AllowOrigin',
        ),
    ]
