# Generated by Django 4.0.4 on 2022-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoip', '0003_sauce_sandwich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='sauces',
            field=models.ManyToManyField(related_name='sandwiches', to='aoip.sauce'),
        ),
    ]
